{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "id": "378d4c8c",
   "metadata": {},
   "source": [
    "### Daten importieren"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "595e3437",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import numpy as np"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "id": "d0126454",
   "metadata": {},
   "source": [
    "### Daten auslesen"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "19cf348f",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('flower_data.csv')\n",
    "\n",
    "dict = {'name': 'Name',\n",
    "        'height (cm)': 'Höhe',\n",
    "        'longevity (years)': 'Lebenserwartung',\n",
    "        'place of origin': 'Herkunftskontinent',\n",
    "        'color': 'Farbe',\n",
    "        'climate': 'Klima',\n",
    "        'cut flowers': 'Geschnittene Blume',\n",
    "        'perfumes': 'Parfum',\n",
    "        'medicine': 'Medizin',\n",
    "        'average number of petals': 'Durchschnittliche Anzhal Blätter'}\n",
    "\n",
    "df.rename(columns=dict, inplace=True)\n",
    "\n",
    "display(df)"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "id": "096d718e",
   "metadata": {},
   "source": [
    "### Daten filtern"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4aadb4cd",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Split the \"Herkunftskontinent\" column\n",
    "df[\"Herkunftskontinent\"] = df[\"Herkunftskontinent\"].str.split(\", \")\n",
    "\n",
    "# Explode the DataFrame\n",
    "df = df.explode(\"Herkunftskontinent\")\n",
    "\n",
    "# Filter the DataFrame for \"Asia\" and \"Europe\"\n",
    "df_filtered = df.loc[df[\"Herkunftskontinent\"].isin([\"Asia\", \"Europe\"])]\n",
    "\n",
    "# Print the resulting DataFrame\n",
    "df_filtered.head()"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "id": "9eb53e91",
   "metadata": {},
   "source": [
    "### Kreis-Diagramm: Herkunftskontinent"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb38047f",
   "metadata": {},
   "outputs": [],
   "source": [
    "font_family = 'Arial'\n",
    "\n",
    "df[\"Herkunftskontinent\"] = df[\"Herkunftskontinent\"].str.split(\", \")\n",
    "df = df.explode(\"Herkunftskontinent\")\n",
    "\n",
    "#counts all instances of continents\n",
    "origin_counts = df[\"Herkunftskontinent\"].value_counts()\n",
    "\n",
    "#plotly pastell color palette\n",
    "colors = px.colors.qualitative.Pastel\n",
    "\n",
    "#creates chart\n",
    "fig = px.pie(values=origin_counts, names=origin_counts.index, title=\"Herkunftskontinent der Blumen\", hole=0.5,\n",
    "             color_discrete_sequence=colors)\n",
    "\n",
    "#layout adjustments\n",
    "fig.update_layout(title={'font': {'family': font_family, 'size': 24}, 'x': 0.5, 'y': 0.9},\n",
    "                  font={'family': font_family, 'size': 12},\n",
    "                  legend_title='Kontinente',\n",
    "                  legend={'x': 0.75,  'y': 0.5})\n",
    "\n",
    "fig.show()"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "id": "c988161c",
   "metadata": {},
   "source": [
    "### Kuchen-Diagramm: Europa vs Asien"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "81b5851b",
   "metadata": {},
   "outputs": [],
   "source": [
    "font_family = 'Arial'\n",
    "\n",
    "asia_europe = df_filtered[\"Herkunftskontinent\"].value_counts()\n",
    "\n",
    "#plotly pastell color palette\n",
    "colors = px.colors.qualitative.Pastel\n",
    "\n",
    "#creates pie chart form asia europe series\n",
    "fig = px.pie(values=asia_europe, names=asia_europe.index, title=\"Asia vs Europe\")\n",
    "                                                                                      \n",
    "#add dropdown\n",
    "\n",
    "#layout adjustments\n",
    "fig.update_layout(\n",
    "    title={'font': {'family': font_family, 'size': 24}, 'x': 0.5, 'y': 0.9},\n",
    "    font={'family': font_family, 'size': 12},\n",
    "    legend_title='Gewählte Kontinente',\n",
    "    legend={'x': 0.7,  'y': 0.5}\n",
    "    )\n",
    "\n",
    "fig.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b5cf3f56",
   "metadata": {},
   "outputs": [],
   "source": [
    "### Aufgabe 5a) and 5b)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aec65936",
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "from dash import Dash, dcc, html, Input, Output\n",
    "import plotly.express as px\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import dash_bootstrap_components as dbc\n",
    "\n",
    "app = Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])\n",
    "\n",
    "# generate random normal distributed data for x and y\n",
    "# and store it in a pandas DataFrame\n",
    "\n",
    "df = pd.DataFrame({'y': np.random.normal(loc=0, scale=10, size=1000),\n",
    "                   'x': np.random.normal(loc=10, scale=2, size=1000)})\n",
    "\n",
    "app.layout = html.Div([html.H1(\"Dashboard 2\"),\n",
    "    dbc.Row([\n",
    "        \n",
    "        dbc.Col([dcc.Dropdown(options=['red', 'green', 'blue'], value='red', id='color', multi=False)], width=6),\n",
    "\n",
    "        ## Aufgabe 5a\n",
    "        dbc.Col([dcc.RangeSlider(min=math.floor(df['y'].min()), max=math.ceil(df['y'].max()), value=[math.floor(df['y'].min()), math.ceil(df['y'].max())], id=\"my-range-slider\")], width=6)\n",
    "        ]),\n",
    "\n",
    "    ## Aufgabe 5b\n",
    "    dbc.Row([\n",
    "        dbc.Col([dcc.Slider(min=math.floor(df['y'].min()), max=math.ceil(df['y'].max()), id=\"min_value\")], width=6),\n",
    "        dbc.Col([dcc.Dropdown(options=['red', 'green', 'blue'], value='red', id='color_2', multi=False)], width=6),\n",
    "    ]),\n",
    "\n",
    "    dbc.Row([dbc.Col([dcc.Graph(id=\"graph_1\")], width=6),\n",
    "             dbc.Col([dcc.Graph(id=\"graph_2\")], width=6)\n",
    "    ])], className=\"m-4\")\n",
    "\n",
    "@app.callback(Output(\"graph_1\", \"figure\"), Input(\"color\", \"value\"), Input(\"min_value\", \"value\"))\n",
    "\n",
    "def update_graph_1(dropdown_value_color, min_value):\n",
    "    dff = df[df['y']> min_value]\n",
    "    fig = px.histogram(dff, x=\"y\", color_discrete_sequence=[dropdown_value_color])\n",
    "    fig.update_layout()\n",
    "    return fig\n",
    "\n",
    "\n",
    "## Aufgabe 5a und 5b\n",
    "@app.callback(Output(\"graph_2\", \"figure\"), [Input(\"my-range-slider\", \"value\"), Input(\"color_2\", \"value\")])\n",
    "\n",
    "def update_graph_2(range_values, color):\n",
    "    dff = df[(df['y'] > range_values[0]) & (df['y'] < range_values[1])]\n",
    "    fig = px.scatter(dff, x='x', y='y', color_discrete_sequence=[color])\n",
    "    fig.update_layout()\n",
    "    return fig\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=False, port=8000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3437bdd6",
   "metadata": {},
   "outputs": [],
   "source": [
    "### Aufgabe 6 a) und b)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "942f9886",
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "from dash import Dash, dcc, html, Input, Output\n",
    "import plotly.express as px\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import dash_bootstrap_components as dbc\n",
    "\n",
    "app = Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])\n",
    "\n",
    "# Random Daten für Tab 1\n",
    "df_random = pd.DataFrame({'y': np.random.normal(loc=0, scale=10, size=1000),\n",
    "                          'x': np.random.normal(loc=10, scale=2, size=1000)})\n",
    "\n",
    "# Unser Datensatz --> für Streudiagrmam aus eigenem Dashboard (graph_3)\n",
    "df_own = pd.read_csv('flower_data.csv')\n",
    "\n",
    "dict = {'name': 'Name',\n",
    "        'height (cm)': 'Höhe',\n",
    "        'longevity (years)': 'Lebenserwartung',\n",
    "        'place of origin': 'Herkunftskontinent',\n",
    "        'color': 'Farbe',\n",
    "        'climate': 'Klima',\n",
    "        'cut flowers': 'Geschnittene Blume',\n",
    "        'perfumes': 'Parfum',\n",
    "        'medicine': 'Medizin',\n",
    "        'average number of petals': 'Durchschnittliche Anzhal Blätter'}\n",
    "\n",
    "df_own.rename(columns=dict, inplace=True)\n",
    "\n",
    "\n",
    "app.layout = html.Div([\n",
    "    html.Div([html.H1(\"Dashboard 3\")], className=\"header\"),\n",
    "    html.Div([\n",
    "        dcc.Tabs(id=\"tabs\", children=[\n",
    "\n",
    "            # Tab 1 (vorgegeben)\n",
    "            dcc.Tab(label='Tab One', id=\"tab_1_graphs\", children=[\n",
    "                html.Div([\n",
    "                    dbc.Row([\n",
    "                        dbc.Col([dcc.Dropdown(options=['red', 'green', 'blue'], value='red', id='color', multi=False)], width=6),\n",
    "                        dbc.Col([dcc.Slider(min=math.floor(df['y'].min()), max=math.ceil(df['y'].max()), id=\"min_value\")], width=6)\n",
    "                    ]),\n",
    "                    dbc.Row([\n",
    "                        dbc.Col([dcc.Graph(id=\"graph_1\")], width=6),\n",
    "                        dbc.Col([dcc.Graph(id=\"graph_2\")], width=6)\n",
    "                    ])\n",
    "                ], className=\"tab_content\")\n",
    "            ]),\n",
    "\n",
    "            # Tab 2 für Aufgabe 6a\n",
    "            dcc.Tab(label='Tab Two', id=\"tab_2_graphs\", children=[\n",
    "    html.Div([\n",
    "                dbc.Row([\n",
    "                    dbc.Col([dcc.Graph(id=\"graph_4\")], width=6)\n",
    "        ])\n",
    "    ])\n",
    "]),\n",
    "\n",
    "            # Tab 3 für Aufgabe 6b\n",
    "            dcc.Tab(label='Tab Three', id=\"tab_3_graphs\", children=[\n",
    "                html.Div([\n",
    "                    dbc.Row([\n",
    "                        dbc.Col([dcc.Graph(id=\"graph_5\")], width=6),\n",
    "                    ])\n",
    "                ])\n",
    "            ])\n",
    "        ])\n",
    "    ])\n",
    "])\n",
    "\n",
    "\n",
    "@app.callback(Output(\"graph_1\", \"figure\"), Input(\"color\", \"value\"))\n",
    "def update_graph_1(dropdown_value_color):\n",
    "    fig = px.histogram(df, x=\"y\", color_discrete_sequence=[dropdown_value_color])\n",
    "    fig.update_layout(template=\"plotly_white\")\n",
    "    return fig\n",
    "\n",
    "\n",
    "@app.callback(Output(\"graph_2\", \"figure\"), Input(\"min_value\", \"value\"))\n",
    "def update_graph_2(min_value):\n",
    "    if min_value:\n",
    "        dff = df[df['y'] > min_value]\n",
    "    else:\n",
    "        dff = df\n",
    "    fig = px.scatter(dff, x='x', y='y')\n",
    "    fig.update_layout(template=\"plotly_white\")\n",
    "    return fig\n",
    "\n",
    "# callback für Aufgabe 6a (graph_3)\n",
    "@app.callback(Output(\"graph_3\", \"figure\"), Input(\"min_value\", \"value\")) \n",
    "def update_graph_3(dropdown_value_color):\n",
    "    fig = px.histogram(df, x=\"Durchschnittliche Anzhal Blätter\", color_discrete_sequence=[dropdown_value_color])\n",
    "    fig.update_layout(template=\"plotly_white\")\n",
    "    return fig\n",
    "\n",
    "# callback für Aufgabe 6b (graph_5)\n",
    "@app.callback(Output(\"graph_5\", \"figure\"), Input(\"min_value\", \"value\"))\n",
    "def update_graph_5(min_value):\n",
    "    if min_value:\n",
    "        dff = df_own[df_own['Höhe'] > min_value]\n",
    "    else:\n",
    "        dff = df_own\n",
    "    fig = px.scatter(dff, x='Durchschnittliche Anzhal Blätter', y=\"Höhe\")\n",
    "    return fig\n",
    "\n",
    "# callback für Balkendiagramm in Tab Two, Aufgabe 6a\n",
    "@app.callback(Output(\"graph_4\", \"figure\"), Input(\"min_value\", \"value\"))\n",
    "def update_graph_4(min_value):\n",
    "    if min_value:\n",
    "        dff = df_own[df_own['Höhe'] > min_value]\n",
    "    else:\n",
    "        dff = df_own\n",
    "    \n",
    "    # Daten für das Balkendiagramm\n",
    "    count_by_color = dff['Farbe'].value_counts()\n",
    "    colors = count_by_color.index.tolist()\n",
    "    counts = count_by_color.tolist()\n",
    "    \n",
    "    # Erstellen des Balkendiagramms\n",
    "    fig = px.bar(x=colors, y=counts)\n",
    "    fig.update_layout(template=\"plotly_white\")\n",
    "    fig.update_xaxes(title=\"Farbe\")\n",
    "    fig.update_yaxes(title=\"Anzahl der Blumen\")\n",
    "    \n",
    "    return fig\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=False, port=8010)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "23ebd4b9",
   "metadata": {},
   "outputs": [],
   "source": [
    "## Testing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "id": "5e1e8b25",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8000/\n",
      "\n",
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 1818, in full_dispatch_request\n",
      "    rv = self.preprocess_request()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\flask\\app.py\", line 2309, in preprocess_request\n",
      "    rv = self.ensure_sync(before_func)()\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\dash.py\", line 1307, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"c:\\Users\\mariu\\anaconda3\\envs\\Testing\\lib\\site-packages\\dash\\_validate.py\", line 408, in validate_layout\n",
      "    raise exceptions.DuplicateIdError(\n",
      "dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `tab_2_graphs`\n"
     ]
    }
   ],
   "source": [
    "import math\n",
    "from dash import Dash, dcc, html, Input, Output\n",
    "import plotly.express as px\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import dash_bootstrap_components as dbc\n",
    "\n",
    "# new: plotly template=\"plotly_white\", https://plotly.com/python/templates/\n",
    "\n",
    "app = Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])\n",
    "\n",
    "df = pd.DataFrame({'y': np.random.normal(loc=0, scale=10, size=1000), 'x': np.random.normal(loc=10, scale=2, size=1000)})\n",
    "\n",
    "app.layout = html.Div([html.Div([html.H1(\"Dashboard 3\")], className=\"header\"), html.Div([dcc.Tabs(id=\"tabs\", children=[\n",
    "            dcc.Tab(label='Tab One', id=\"tab_1_graphs\", children=[html.Div([\n",
    "                dbc.Row([dbc.Col([dcc.Dropdown(options=['red','green','blue'], value='red', id='color', multi=False)], width=6),\n",
    "                         dbc.Col([dcc.Slider(min=math.floor(df['y'].min()),max=math.ceil(df['y'].max()),id=\"min_value\")], width=6)]),\n",
    "                dbc.Row([dbc.Col([dcc.Graph(id=\"graph_1\")],width=6),\n",
    "                         dbc.Col([dcc.Graph(id=\"graph_2\")],width=6)])], className=\"tab_content\"),]),\n",
    "            dcc.Tab(label='Tab Two', id=\"tab_2_graphs\",children=[html.Div([],className=\"tab_content\")]),\n",
    "\n",
    "            #adding athird tab\n",
    "            dcc.Tab(label='Tab Three', id=\"tab_3_graphs\",children=[html.Div([],className=\"tab_content\")]),])], className=\"content\")])\n",
    "\n",
    "@app.callback(Output(\"graph_1\", \"figure\"), Input(\"color\", \"value\"))\n",
    "\n",
    "def update_graph_1(dropdown_value_color):\n",
    "    fig = px.histogram(df, x=\"y\", color_discrete_sequence=[dropdown_value_color])\n",
    "    fig.update_layout(template=\"plotly_white\")\n",
    "    return fig\n",
    "\n",
    "@app.callback(Output(\"graph_2\", \"figure\"),Input(\"min_value\", \"value\"))\n",
    "\n",
    "def update_graph_2(min_value):\n",
    "    if min_value:\n",
    "        dff = df[df['y'] > min_value]\n",
    "    else:\n",
    "        dff = df\n",
    "    fig = px.scatter(dff, x='x', y='y')\n",
    "    fig.update_layout(template=\"plotly_white\")\n",
    "    return fig\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=False, port=8000)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "DADE",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
